### PR TITLE
Update nushell crates

### PR DESCRIPTION
**Pull request by diniamo**
## Description of changes

Updates the nushell crates, and adjusts the code according to the breaking changes.

## Relevant Issues

NixOS/nixpkgs#341647

### CODE REVIEW

**Comment by diniamo** [comment]
No clue why that test fails

**Comment by AucaCoyan** [comment]
Hi! thank you for updating the deps.
Apparently the parser got updates since 0.88.1 and now it parses things a little different.

I test it on my pc and the result of the test `ignore_comments` is

```rust
        let expected = "# beginning of script comment
let one = 1
def my-func [
    param1:int # inline comment
]{ print(param1) 
}
myfunc (one )
# final comment";
```

(a little space difference in the line `myfunc (one )`

**Comment by diniamo** [comment]
Yeah I got that far as well, but is that actually the result we want? I wouldn't want my function calls looking like that.

**Comment by AucaCoyan** [comment]
Sure, it can (and should eventually) be fixed, but I prefer to merge this as is and then in another pr fix/improve the formatter logic and after change the tests that looks weird.
Isn't it better?

**Comment by fdncred** [comment]
ok, i'll land it if someone fixes the problem.

**Comment by diniamo** [comment]
Well, I'm fine either way. I don't even use nu, I just wanted to get the development environment working (couldn't for 3 different reasons), and try it.

I might wait with updating the nixpkgs PR until someone fixes it though.

**Pull request merged**
