### PR TITLE
Revert "Check Nix flake workflow (#46)"

### PR DESCRIPTION
**Pull request by amtoine**
related to
- #46

cc/ @IogaMaster 

## Description of changes
this PR reverts #46.

without any justification for this, i'd rather revert the changes :yum:

### CODE REVIEW

**Comment by IogaMaster** [comment]
This makes sure the flake is functional and doesn't error when someone wants to enter the devshell or build nufmt with nix.

**Comment by amtoine** [comment]
we'll decide the fate of that PR from https://github.com/nushell/nufmt/pull/52 :wink:

**Comment by IogaMaster** [comment]
#53 Happens anyway because the flake syntax is valid but the package itself built for macos needs Iokit to build.

**Comment by IogaMaster** [comment]
So if we dont merge #52 then I will write a check that runs on macos to test builds there as well.

**Comment by amtoine** [comment]
#46 has been sorted out, thanks @IogaMaster for the explaining :pray:

**Pull request closed without merging**
