### PR TITLE
Basic Flake

### PR DESCRIPTION
**Pull request by IogaMaster**
Here is a basic flake for the project.

Features:
- Multi architecture builds (aarch64, x86_64, risc, etc)
- Reproducible development environments. Run `nix develop` and you have the locked version of Rust and rust-analyzer
- Reproducable builds.

Let me know any other changes that need to be made

### CODE REVIEW

**Comment by IogaMaster** [comment]
Do i need to fix the format issue, the pr doesn't contain rust code.

**Comment by fdncred** [comment]
weird that we'd have a fmt problem here where there's no rust code. maybe we should have a separate pr to fix the fmt issue since it's unrelated to this pr. if something crazy happened and we had to revert this PR, we probably wouldn't want to revert the fmt change.

**Comment by IogaMaster** [comment]
I'll see about fixing that in a separate pr

**Comment by IogaMaster** [comment]
Also would we want direnv for automatic runs of `nix develop` when applicable.
https://github.com/direnv/direnv

**Comment by IogaMaster** [comment]
https://github.com/nushell/nufmt/pull/43

**Comment by fdncred** [comment]
> Also would we want direnv for automatic runs of `nix develop` when applicable. https://github.com/direnv/direnv

I'm agnostic on direnv. I know some people use it and love it. Others don't. One key that we always have to keep in mind is that nufmt, and the nushell family of programs, aren't just Linux or Mac programs.  We need to continue to try to be as cross-platform as possible and support Windows.

**Comment by IogaMaster** [comment]
Nix is not on windows but it would be just for mac and linux devs same as the direnv thing as it would use nix-direnv

**Comment by IogaMaster** [comment]
I want to remove the merge commit first

**Comment by fdncred** [comment]
> I like to have Nix be optional to developing a project, just a nice addition.

Right. I'm not objecting to this as an optional thing at all. Just reminding onlookers that we're cross-platform, so every PR will be seen in that light.

**Comment by fdncred** [comment]
Thanks

**Pull request merged**
